### ISSUE TITLE
可以提供一下ppbc数据集吗

### ISSUE THREAD

**Issue by lztry** [chuan0717/pytorch-VGG16#1]
您好，使用您的脚本，结果在爬取图片的时候总是显示

`'Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None`
错误，所以您能提供下数据集吗？不用做商业用途，硕士毕设使用。如有提供感激不尽。救救孩子吧
邮箱 26674193102qq.com

**Comment by chuan0717** [comment]
您好，首先这个error的抛出可能是被网站识别成了攻击行为，但我已经设置了time爬取是有时间间隔的，所以我觉得你的问题应该出在其他地方，刚刚找到一篇文章应该比较全 [https://www.jianshu.com/p/d8585f0d9eb8]，您可以试一下。至于数据集真的很遗憾，那个u盘我已经找不到了，而且我只爬取了每种植物20张图，您需要根据自己情况设置。

**Comment by lztry** [comment]
谢谢。看了您的代码受到很大启发。
`  x = chapter_photo.find('http')
  url2 = chapter_photo[x : -4]
  r = requests.get(url2, headers = headers)`
在获取图片url 存在点问题，可能由于网页结构的改变，导致抓取的URL中，包含好多html <img>标签,这时候，在这样获取会获得好多冗余数据。建议将find 修改为rfind,这样就能正确获取网址，或者用bs4 解析就更加准确。

**Comment by chuan0717** [comment]
很感谢您对我的评价和建议！以后的学习中我会受到很多启发

**Comment by lztry** [comment]
问题解决，谢谢
